import sys

# Build the replacement text line by line
L = []
def a(s): L.append(s)

a("        def _rebuild_fd():")
a("            fixture_data.clear()")
a("            for i, proj in enumerate(self.projectors):")
a("                fixture_data.append({")
a("                    'name':          proj.name or proj.group,")
a("                    'fixture_type':  getattr(proj, 'fixture_type', 'PAR LED'),")
a("                    'group':         proj.group,")
a("                    'start_address': proj.start_address,")
a("                    'profile':       list(self.dmx._get_profile(f"{proj.group}_{i}")),")
a("                })")
a("")
a("        _rebuild_fd()")
a("")
a("        def _get_conflicts():")
a("            occ = {}")
a("            for i, fd in enumerate(fixture_data):")
a("                for c in range(fd['start_address'], fd['start_address'] + len(fd['profile'])):")
a("                    occ.setdefault(c, []).append(i)")
a("            return {i for lst in occ.values() if len(lst) > 1 for i in lst}")
a("")
a("        def _update_conflict_banner(conflicts):")
a("            if conflicts and tabs.currentIndex() == 0:")
a("                n = len(conflicts)")
a("                conflict_banner.setText(")
a("                    f"  ⚠  {n} fixture{'s' if n > 1 else ''} avec des canaux DMX qui se chevauchent"")
a("                    "  —  utilisez ⚡ Auto-addr. pour corriger"")
a("                )")
a("                conflict_banner.setVisible(True)")
a("            else:")
a("                conflict_banner.setVisible(False)")
a("")
a("        tabs.currentChanged.connect(lambda _: _update_conflict_banner(_get_conflicts()))")
a("")

text = chr(10).join(L)
with open(r"C:/Users/nikop/Desktop/MyStrow/App/_replacement.py", "w", encoding="utf-8") as f:
    f.write(text)
print("partial written, lines:", len(L))
